---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
  ports:
  - port: 80
    name: http-user
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: yosz328/user_service_dev
        ports:
        - name: http-api
          containerPort: 8080
        resources:
          limits:
            cpu: "0.1"
            memory: 900Mi
