---
apiVersion: v1
kind: Service
metadata:
  name: google
spec:
  selector:
    app: google
  ports:
  - port: 80
    name: http-google
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: google
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: google
    spec:
      containers:
      - name: google
        image: yosz328/google_service
        ports:
        - name: http-api
          containerPort: 8081
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
